### ISSUE TITLE
Removal of fluent interface

### ISSUE THREAD

**Issue by sagikazarmark** [fuelphp/display#11]
I am willing to remove fluent interface from display package.

@WanWizard any objections?

**Comment by sagikazarmark** [comment]
Any objections?

**Comment by stevewest** [comment]
The only thing I have ever chained with views is multiple calls of `set()` to make the code clearer and to make turning output filtering off clearer too. I'm with @sagikazarmark in that fluent interfaces should be avoided for the most part.

If people request it we can easily add it back in at a later date.

**Comment by WanWizard** [comment]
I agree it should not be there "for the sake of it", but don't remove it where is absolutely makes sense.

For views, it absolutely makes sense to be able to chain the diffent set() methods. This may have side effects though, for example simply returning the result of a chained call and expect to get a View object back may no longer work depending on the last method in the chain.

**Comment by sagikazarmark** [comment]
Yeah, the builder-like methods can be fluent.

**Comment by sagikazarmark** [comment]
> for example simply returning the result of a chained call and expect to get a View object back may no longer work depending on the last method in the chain.

@WanWizard that's the responsibility of the developer
